# Generated by Django 3.1 on 2020-11-21 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ControlDeVeterinaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cirugias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cirugia', models.CharField(max_length=30)),
                ('mascota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ControlDeVeterinaria.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfermedad', models.CharField(max_length=30)),
                ('mascota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ControlDeVeterinaria.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Otros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otro', models.CharField(max_length=30)),
                ('mascota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ControlDeVeterinaria.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacuna', models.CharField(max_length=30)),
                ('mascota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ControlDeVeterinaria.mascota')),
            ],
        ),
        migrations.DeleteModel(
            name='Expediente',
        ),
    ]
