# Generated by Django 3.1 on 2020-12-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlDeVeterinaria', '0003_cita_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('rol', models.CharField(choices=[('ADMIN', 'ADMIN'), ('EMPLEADO', 'EMPLEADO')], max_length=30)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('paswword', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
