# Generated by Django 3.1 on 2020-12-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlDeVeterinaria', '0005_auto_20201130_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='paswword',
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
